#ifndef _XSM_CONSTANTS_H

#define XSM_CONSTANTS_H

#define XSM_WORD_SIZE 16
#define XSM_MEMORY_NUMPAGES 128
#define XSM_PAGE_SIZE 512

#define XSM_REGSIZE XSM_WORD_SIZE
#define XSM_NUM_REG 33

#define XSM_ILLINSTR -1

#define XSM_SUCCESS 1
#define XSM_FAILURE 0

#define XSM_INSTRUCTION_SIZE 2

#endif
